### ISSUE TITLE
project not building

### ISSUE THREAD

**Issue by moh1122** [UberJason/TrackIt#1]
Hello nice app
But its not building i have an error saying:

/Users/Apple/Library/Developer/Xcode/DerivedData/TrackIt-hbuolbmwfnslkndvoubweoymqfuj/Build/Intermediates/TrackIt.build/Debug-iphonesimulator/TrackIt.build/Script-1FB3DD4D7A0B88D8467C9383.sh: line 2: /Users/Apple/Downloads/TrackIt-master/TrackIt-master/Pods/Target Support Files/Pods-TrackIt/Pods-TrackIt-frameworks.sh: Permission denied

any clue?
Thank you

**Comment by UberJason** [comment]
Hmm not sure - did you try deleting derived data and trying again?

**Comment by moh1122** [comment]
yes i did
?

**Comment by UberJason** [comment]
Have you set up Cocoapods correctly? The project uses Cocoapods. For example, try running 'pod install', open the project in the xcworkspace rather than the xcodeproj, etc. I don't really have any other thoughts I could give.

**Comment by moh1122** [comment]
im opening it in xcworkspace and its still the same?

**Comment by UberJason** [comment]
Have you set up Cocoapods correctly?

**Comment by moh1122** [comment]
how to do tht i only opened xcworkspace project?

**Comment by UberJason** [comment]
Have a look at the documentation here:

https://cocoapods.org
